/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AABAwindowSupprimer (void);
GtkWidget* create_AABAwindowAjouter (void);
GtkWidget* create_AABAwindowModifier (void);
GtkWidget* create_AABAwindowGererParking (void);
GtkWidget* create_AABAwindowAttribuerAgent (void);
