/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_AABAwindowSupprimer (void)
{
  GtkWidget *AABAwindowSupprimer;
  GtkWidget *AABAfixedSupprimer;
  GtkWidget *AABAlabelSupprimerAsk;
  GtkWidget *AABAlabelSupprimerTitle;
  GtkWidget *AABAbuttonSupprimerOui;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label11;
  GtkWidget *AABAbuttonSupprimerNon;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label12;
  GtkWidget *AABAlabelSupprimerParkingName;

  AABAwindowSupprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AABAwindowSupprimer), _("Supprimer Parking"));

  AABAfixedSupprimer = gtk_fixed_new ();
  gtk_widget_show (AABAfixedSupprimer);
  gtk_container_add (GTK_CONTAINER (AABAwindowSupprimer), AABAfixedSupprimer);
  gtk_widget_set_size_request (AABAfixedSupprimer, 400, 300);

  AABAlabelSupprimerAsk = gtk_label_new (_("Voulez vous vraiment supprimer ce parking?"));
  gtk_widget_show (AABAlabelSupprimerAsk);
  gtk_fixed_put (GTK_FIXED (AABAfixedSupprimer), AABAlabelSupprimerAsk, 96, 104);
  gtk_widget_set_size_request (AABAlabelSupprimerAsk, 219, 67);
  gtk_label_set_justify (GTK_LABEL (AABAlabelSupprimerAsk), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (AABAlabelSupprimerAsk), TRUE);

  AABAlabelSupprimerTitle = gtk_label_new (_("Supprimer Parking:"));
  gtk_widget_show (AABAlabelSupprimerTitle);
  gtk_fixed_put (GTK_FIXED (AABAfixedSupprimer), AABAlabelSupprimerTitle, 104, 32);
  gtk_widget_set_size_request (AABAlabelSupprimerTitle, 200, 17);

  AABAbuttonSupprimerOui = gtk_button_new ();
  gtk_widget_show (AABAbuttonSupprimerOui);
  gtk_fixed_put (GTK_FIXED (AABAfixedSupprimer), AABAbuttonSupprimerOui, 240, 216);
  gtk_widget_set_size_request (AABAbuttonSupprimerOui, 100, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (AABAbuttonSupprimerOui), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Oui"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox11), label11, FALSE, FALSE, 0);

  AABAbuttonSupprimerNon = gtk_button_new ();
  gtk_widget_show (AABAbuttonSupprimerNon);
  gtk_fixed_put (GTK_FIXED (AABAfixedSupprimer), AABAbuttonSupprimerNon, 56, 216);
  gtk_widget_set_size_request (AABAbuttonSupprimerNon, 100, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (AABAbuttonSupprimerNon), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Non"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox12), label12, FALSE, FALSE, 0);

  AABAlabelSupprimerParkingName = gtk_label_new ("");
  gtk_widget_show (AABAlabelSupprimerParkingName);
  gtk_fixed_put (GTK_FIXED (AABAfixedSupprimer), AABAlabelSupprimerParkingName, 50, 56);
  gtk_widget_set_size_request (AABAlabelSupprimerParkingName, 300, 17);

  g_signal_connect ((gpointer) AABAwindowSupprimer, "map",
                    G_CALLBACK (on_AABAwindowSupprimer_map),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonSupprimerOui, "clicked",
                    G_CALLBACK (on_AABAbuttonSupprimerOui_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonSupprimerNon, "clicked",
                    G_CALLBACK (on_AABAbuttonSupprimerNon_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AABAwindowSupprimer, AABAwindowSupprimer, "AABAwindowSupprimer");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, AABAfixedSupprimer, "AABAfixedSupprimer");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, AABAlabelSupprimerAsk, "AABAlabelSupprimerAsk");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, AABAlabelSupprimerTitle, "AABAlabelSupprimerTitle");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, AABAbuttonSupprimerOui, "AABAbuttonSupprimerOui");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, image11, "image11");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, label11, "label11");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, AABAbuttonSupprimerNon, "AABAbuttonSupprimerNon");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, image12, "image12");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, label12, "label12");
  GLADE_HOOKUP_OBJECT (AABAwindowSupprimer, AABAlabelSupprimerParkingName, "AABAlabelSupprimerParkingName");

  return AABAwindowSupprimer;
}

GtkWidget*
create_AABAwindowAjouter (void)
{
  GtkWidget *AABAwindowAjouter;
  GtkWidget *AABAfixedAjouter;
  GtkWidget *AABAtextviewAjouterLocalization;
  GtkObject *AABAspinbuttonNombreDePlaces_adj;
  GtkWidget *AABAspinbuttonNombreDePlaces;
  GtkObject *AABAspinbuttonAjouterTarif_adj;
  GtkWidget *AABAspinbuttonAjouterTarif;
  GtkWidget *AABAentryAjouterNom;
  GtkWidget *AABAlabelAjouterLocalisation;
  GtkWidget *AABAlabelAjouterType;
  GtkWidget *AABAlabelAjouterNombreDePlaces;
  GtkWidget *AABAlabelAjouterHrsDouv;
  GtkWidget *AABAlabelAjouterOuv;
  GtkWidget *AABAlabelAjouterFerm;
  GtkWidget *AABAlabelAjouterTarif;
  GtkWidget *AABAlabelAjouterTitle;
  GtkWidget *AABAlabelAjouterNom;
  GtkWidget *AABAcomboboxAjouterOuv;
  GtkWidget *AABAcomboboxAjouterFerm;
  GtkWidget *AABAbuttonAjouterEnregistrer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *AABAcomboboxAjouterType;
  GtkWidget *AABAcheckbuttonAjouter247;
  GtkWidget *AABAbuttonAnnuler;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *AABAlabelAjouterError;

  AABAwindowAjouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AABAwindowAjouter), _("Ajouter Parking"));

  AABAfixedAjouter = gtk_fixed_new ();
  gtk_widget_show (AABAfixedAjouter);
  gtk_container_add (GTK_CONTAINER (AABAwindowAjouter), AABAfixedAjouter);
  gtk_widget_set_size_request (AABAfixedAjouter, 500, 600);
  gtk_container_set_border_width (GTK_CONTAINER (AABAfixedAjouter), 5);

  AABAtextviewAjouterLocalization = gtk_text_view_new ();
  gtk_widget_show (AABAtextviewAjouterLocalization);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAtextviewAjouterLocalization, 152, 112);
  gtk_widget_set_size_request (AABAtextviewAjouterLocalization, 256, 64);
  gtk_container_set_border_width (GTK_CONTAINER (AABAtextviewAjouterLocalization), 5);

  AABAspinbuttonNombreDePlaces_adj = gtk_adjustment_new (1, 1, 1000, 1, 20, 20);
  AABAspinbuttonNombreDePlaces = gtk_spin_button_new (GTK_ADJUSTMENT (AABAspinbuttonNombreDePlaces_adj), 1, 0);
  gtk_widget_show (AABAspinbuttonNombreDePlaces);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAspinbuttonNombreDePlaces, 152, 256);
  gtk_widget_set_size_request (AABAspinbuttonNombreDePlaces, 256, 27);

  AABAspinbuttonAjouterTarif_adj = gtk_adjustment_new (1, 1, 500, 1, 20, 20);
  AABAspinbuttonAjouterTarif = gtk_spin_button_new (GTK_ADJUSTMENT (AABAspinbuttonAjouterTarif_adj), 1, 0);
  gtk_widget_show (AABAspinbuttonAjouterTarif);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAspinbuttonAjouterTarif, 152, 432);
  gtk_widget_set_size_request (AABAspinbuttonAjouterTarif, 256, 27);

  AABAentryAjouterNom = gtk_entry_new ();
  gtk_widget_show (AABAentryAjouterNom);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAentryAjouterNom, 150, 64);
  gtk_widget_set_size_request (AABAentryAjouterNom, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (AABAentryAjouterNom), 8226);

  AABAlabelAjouterLocalisation = gtk_label_new (_("Localisation:"));
  gtk_widget_show (AABAlabelAjouterLocalisation);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterLocalisation, 8, 112);
  gtk_widget_set_size_request (AABAlabelAjouterLocalisation, 127, 17);

  AABAlabelAjouterType = gtk_label_new (_("Type:"));
  gtk_widget_show (AABAlabelAjouterType);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterType, 16, 200);
  gtk_widget_set_size_request (AABAlabelAjouterType, 127, 17);

  AABAlabelAjouterNombreDePlaces = gtk_label_new (_("Nombre de places:"));
  gtk_widget_show (AABAlabelAjouterNombreDePlaces);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterNombreDePlaces, 16, 256);
  gtk_widget_set_size_request (AABAlabelAjouterNombreDePlaces, 127, 17);

  AABAlabelAjouterHrsDouv = gtk_label_new (_("Heures D'ouverture:"));
  gtk_widget_show (AABAlabelAjouterHrsDouv);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterHrsDouv, 8, 304);
  gtk_widget_set_size_request (AABAlabelAjouterHrsDouv, 155, 19);

  AABAlabelAjouterOuv = gtk_label_new (_("Ouverture:"));
  gtk_widget_show (AABAlabelAjouterOuv);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterOuv, 88, 344);
  gtk_widget_set_size_request (AABAlabelAjouterOuv, 83, 19);

  AABAlabelAjouterFerm = gtk_label_new (_("Fermeture:"));
  gtk_widget_show (AABAlabelAjouterFerm);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterFerm, 88, 376);
  gtk_widget_set_size_request (AABAlabelAjouterFerm, 83, 19);

  AABAlabelAjouterTarif = gtk_label_new (_("Tarif Heuraire:"));
  gtk_widget_show (AABAlabelAjouterTarif);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterTarif, 8, 432);
  gtk_widget_set_size_request (AABAlabelAjouterTarif, 127, 17);

  AABAlabelAjouterTitle = gtk_label_new (_("Ajouter Parking"));
  gtk_widget_show (AABAlabelAjouterTitle);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterTitle, 150, 16);
  gtk_widget_set_size_request (AABAlabelAjouterTitle, 200, 17);

  AABAlabelAjouterNom = gtk_label_new (_("Nom du parking:"));
  gtk_widget_show (AABAlabelAjouterNom);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterNom, 16, 64);
  gtk_widget_set_size_request (AABAlabelAjouterNom, 127, 17);

  AABAcomboboxAjouterOuv = gtk_combo_box_new_text ();
  gtk_widget_show (AABAcomboboxAjouterOuv);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAcomboboxAjouterOuv, 184, 344);
  gtk_widget_set_size_request (AABAcomboboxAjouterOuv, 67, 27);
  gtk_container_set_border_width (GTK_CONTAINER (AABAcomboboxAjouterOuv), 5);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("00:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("00:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("01:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("01:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("02:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("02:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("03:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("03:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("04:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("04:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("05:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("05:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("06:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("06:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("07:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("07:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("08:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("08:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("09:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("09:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("10:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("10:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("11:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("11:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("12:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("12:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("13:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("13:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("14:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("14:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("15:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("15:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("16:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("16:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("17:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("17:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("18:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("18:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("19:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("19:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("20:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("20:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("21:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("21:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("22:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("22:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("23:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterOuv), _("23:30"));

  AABAcomboboxAjouterFerm = gtk_combo_box_new_text ();
  gtk_widget_show (AABAcomboboxAjouterFerm);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAcomboboxAjouterFerm, 184, 376);
  gtk_widget_set_size_request (AABAcomboboxAjouterFerm, 67, 27);
  gtk_container_set_border_width (GTK_CONTAINER (AABAcomboboxAjouterFerm), 5);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("00:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("00:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("01:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("01:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("02:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("02:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("03:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("03:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("04:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("04:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("05:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("05:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("06:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("06:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("07:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("07:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("08:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("08:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("09:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("09:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("10:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("10:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("11:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("11:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("12:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("12:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("13:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("13:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("14:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("14:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("15:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("15:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("16:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("16:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("17:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("17:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("18:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("18:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("19:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("19:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("20:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("20:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("21:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("21:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("22:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("22:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("23:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterFerm), _("23:30"));

  AABAbuttonAjouterEnregistrer = gtk_button_new ();
  gtk_widget_show (AABAbuttonAjouterEnregistrer);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAbuttonAjouterEnregistrer, 300, 530);
  gtk_widget_set_size_request (AABAbuttonAjouterEnregistrer, 120, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (AABAbuttonAjouterEnregistrer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  AABAcomboboxAjouterType = gtk_combo_box_new_text ();
  gtk_widget_show (AABAcomboboxAjouterType);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAcomboboxAjouterType, 152, 200);
  gtk_widget_set_size_request (AABAcomboboxAjouterType, 256, 35);
  gtk_container_set_border_width (GTK_CONTAINER (AABAcomboboxAjouterType), 5);
  GTK_WIDGET_SET_FLAGS (AABAcomboboxAjouterType, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterType), _("Interieur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterType), _("Exterieur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxAjouterType), _("Sous-terrain"));

  AABAcheckbuttonAjouter247 = gtk_check_button_new_with_mnemonic (_("24/7"));
  gtk_widget_show (AABAcheckbuttonAjouter247);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAcheckbuttonAjouter247, 160, 304);
  gtk_widget_set_size_request (AABAcheckbuttonAjouter247, 120, 24);

  AABAbuttonAnnuler = gtk_button_new ();
  gtk_widget_show (AABAbuttonAnnuler);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAbuttonAnnuler, 80, 530);
  gtk_widget_set_size_request (AABAbuttonAnnuler, 120, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (AABAbuttonAnnuler), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  AABAlabelAjouterError = gtk_label_new ("");
  gtk_widget_show (AABAlabelAjouterError);
  gtk_fixed_put (GTK_FIXED (AABAfixedAjouter), AABAlabelAjouterError, 50, 480);
  gtk_widget_set_size_request (AABAlabelAjouterError, 400, 40);

  g_signal_connect ((gpointer) AABAbuttonAjouterEnregistrer, "clicked",
                    G_CALLBACK (on_AABAbuttonAjouterEnregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAcheckbuttonAjouter247, "toggled",
                    G_CALLBACK (on_AABAcheckbuttonAjouter247_toggled),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonAnnuler, "clicked",
                    G_CALLBACK (on_AABAbuttonAnnuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AABAwindowAjouter, AABAwindowAjouter, "AABAwindowAjouter");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAfixedAjouter, "AABAfixedAjouter");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAtextviewAjouterLocalization, "AABAtextviewAjouterLocalization");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAspinbuttonNombreDePlaces, "AABAspinbuttonNombreDePlaces");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAspinbuttonAjouterTarif, "AABAspinbuttonAjouterTarif");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAentryAjouterNom, "AABAentryAjouterNom");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterLocalisation, "AABAlabelAjouterLocalisation");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterType, "AABAlabelAjouterType");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterNombreDePlaces, "AABAlabelAjouterNombreDePlaces");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterHrsDouv, "AABAlabelAjouterHrsDouv");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterOuv, "AABAlabelAjouterOuv");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterFerm, "AABAlabelAjouterFerm");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterTarif, "AABAlabelAjouterTarif");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterTitle, "AABAlabelAjouterTitle");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterNom, "AABAlabelAjouterNom");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAcomboboxAjouterOuv, "AABAcomboboxAjouterOuv");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAcomboboxAjouterFerm, "AABAcomboboxAjouterFerm");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAbuttonAjouterEnregistrer, "AABAbuttonAjouterEnregistrer");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, image3, "image3");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, label3, "label3");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAcomboboxAjouterType, "AABAcomboboxAjouterType");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAcheckbuttonAjouter247, "AABAcheckbuttonAjouter247");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAbuttonAnnuler, "AABAbuttonAnnuler");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, image4, "image4");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, label4, "label4");
  GLADE_HOOKUP_OBJECT (AABAwindowAjouter, AABAlabelAjouterError, "AABAlabelAjouterError");

  gtk_widget_grab_default (AABAcomboboxAjouterType);
  return AABAwindowAjouter;
}

GtkWidget*
create_AABAwindowModifier (void)
{
  GtkWidget *AABAwindowModifier;
  GtkWidget *AABAfixedModifier;
  GtkWidget *AABAentryModifierNom;
  GtkWidget *AABAtextviewModifierLoc;
  GtkObject *AABAspinbuttonModifierNumDePlaces_adj;
  GtkWidget *AABAspinbuttonModifierNumDePlaces;
  GtkObject *AABAspinbuttonModifierTarif_adj;
  GtkWidget *AABAspinbuttonModifierTarif;
  GtkWidget *AABAlabelModifierLoc;
  GtkWidget *AABAlabelModifierNumDePlaces;
  GtkWidget *AABAlabelModifierHrsDouv;
  GtkWidget *AABAlabelModifierOuv;
  GtkWidget *AABAlabelModifierFerm;
  GtkWidget *AABAlabelModifierTarif;
  GtkWidget *AABAlabelModifierTitle;
  GtkWidget *AABAlabelModifierNom;
  GtkWidget *AABAlabelModifierType;
  GtkWidget *AABAcomboboxModifierOuv;
  GtkWidget *AABAcomboboxModifierFerm;
  GtkWidget *AABAcomboboxModifierType;
  GtkWidget *AABAbuttonModifierAnnuler;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *AABAbuttonModifierEnregistrer;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *AABAlabelModifierError;
  GtkWidget *AABAcheckbuttonModifier247;

  AABAwindowModifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AABAwindowModifier), _("Modifier Parking"));

  AABAfixedModifier = gtk_fixed_new ();
  gtk_widget_show (AABAfixedModifier);
  gtk_container_add (GTK_CONTAINER (AABAwindowModifier), AABAfixedModifier);
  gtk_widget_set_size_request (AABAfixedModifier, 500, 600);
  gtk_container_set_border_width (GTK_CONTAINER (AABAfixedModifier), 5);

  AABAentryModifierNom = gtk_entry_new ();
  gtk_widget_show (AABAentryModifierNom);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAentryModifierNom, 150, 64);
  gtk_widget_set_size_request (AABAentryModifierNom, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (AABAentryModifierNom), 8226);

  AABAtextviewModifierLoc = gtk_text_view_new ();
  gtk_widget_show (AABAtextviewModifierLoc);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAtextviewModifierLoc, 152, 112);
  gtk_widget_set_size_request (AABAtextviewModifierLoc, 256, 64);
  gtk_container_set_border_width (GTK_CONTAINER (AABAtextviewModifierLoc), 5);

  AABAspinbuttonModifierNumDePlaces_adj = gtk_adjustment_new (1, 1, 1000, 1, 20, 20);
  AABAspinbuttonModifierNumDePlaces = gtk_spin_button_new (GTK_ADJUSTMENT (AABAspinbuttonModifierNumDePlaces_adj), 1, 0);
  gtk_widget_show (AABAspinbuttonModifierNumDePlaces);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAspinbuttonModifierNumDePlaces, 152, 256);
  gtk_widget_set_size_request (AABAspinbuttonModifierNumDePlaces, 256, 27);

  AABAspinbuttonModifierTarif_adj = gtk_adjustment_new (1, 1, 500, 1, 20, 20);
  AABAspinbuttonModifierTarif = gtk_spin_button_new (GTK_ADJUSTMENT (AABAspinbuttonModifierTarif_adj), 1, 0);
  gtk_widget_show (AABAspinbuttonModifierTarif);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAspinbuttonModifierTarif, 152, 432);
  gtk_widget_set_size_request (AABAspinbuttonModifierTarif, 256, 27);

  AABAlabelModifierLoc = gtk_label_new (_("Localisation:"));
  gtk_widget_show (AABAlabelModifierLoc);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierLoc, 8, 112);
  gtk_widget_set_size_request (AABAlabelModifierLoc, 127, 17);

  AABAlabelModifierNumDePlaces = gtk_label_new (_("Nombre de places:"));
  gtk_widget_show (AABAlabelModifierNumDePlaces);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierNumDePlaces, 16, 256);
  gtk_widget_set_size_request (AABAlabelModifierNumDePlaces, 127, 17);

  AABAlabelModifierHrsDouv = gtk_label_new (_("Heures D'ouverture"));
  gtk_widget_show (AABAlabelModifierHrsDouv);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierHrsDouv, 8, 304);
  gtk_widget_set_size_request (AABAlabelModifierHrsDouv, 155, 19);

  AABAlabelModifierOuv = gtk_label_new (_("Ouverture:"));
  gtk_widget_show (AABAlabelModifierOuv);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierOuv, 88, 344);
  gtk_widget_set_size_request (AABAlabelModifierOuv, 83, 19);

  AABAlabelModifierFerm = gtk_label_new (_("Fermeture:"));
  gtk_widget_show (AABAlabelModifierFerm);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierFerm, 88, 376);
  gtk_widget_set_size_request (AABAlabelModifierFerm, 83, 19);

  AABAlabelModifierTarif = gtk_label_new (_("Tarif Heuraire:"));
  gtk_widget_show (AABAlabelModifierTarif);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierTarif, 8, 432);
  gtk_widget_set_size_request (AABAlabelModifierTarif, 127, 17);

  AABAlabelModifierTitle = gtk_label_new (_("Modifier Parking"));
  gtk_widget_show (AABAlabelModifierTitle);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierTitle, 150, 16);
  gtk_widget_set_size_request (AABAlabelModifierTitle, 200, 17);

  AABAlabelModifierNom = gtk_label_new (_("Nom du parking:"));
  gtk_widget_show (AABAlabelModifierNom);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierNom, 16, 64);
  gtk_widget_set_size_request (AABAlabelModifierNom, 127, 17);

  AABAlabelModifierType = gtk_label_new (_("Type:"));
  gtk_widget_show (AABAlabelModifierType);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierType, 16, 200);
  gtk_widget_set_size_request (AABAlabelModifierType, 127, 17);

  AABAcomboboxModifierOuv = gtk_combo_box_new_text ();
  gtk_widget_show (AABAcomboboxModifierOuv);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAcomboboxModifierOuv, 184, 344);
  gtk_widget_set_size_request (AABAcomboboxModifierOuv, 67, 27);
  gtk_container_set_border_width (GTK_CONTAINER (AABAcomboboxModifierOuv), 5);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("00:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("00:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("01:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("01:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("02:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("02:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("03:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("03:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("04:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("04:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("05:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("05:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("06:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("06:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("07:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("07:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("08:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("08:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("09:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("09:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("10:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("10:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("11:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("11:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("12:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("12:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("13:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("13:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("14:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("14:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("15:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("15:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("16:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("16:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("17:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("17:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("18:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("18:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("19:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("19:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("20:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("20:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("21:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("21:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("22:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("22:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("23:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierOuv), _("23:30"));

  AABAcomboboxModifierFerm = gtk_combo_box_new_text ();
  gtk_widget_show (AABAcomboboxModifierFerm);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAcomboboxModifierFerm, 184, 376);
  gtk_widget_set_size_request (AABAcomboboxModifierFerm, 67, 27);
  gtk_container_set_border_width (GTK_CONTAINER (AABAcomboboxModifierFerm), 5);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("00:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("00:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("01:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("01:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("02:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("02:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("03:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("03:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("04:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("04:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("05:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("05:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("06:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("06:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("07:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("07:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("08:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("08:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("09:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("09:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("10:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("10:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("11:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("11:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("12:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("12:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("13:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("13:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("14:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("14:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("15:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("15:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("16:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("16:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("17:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("17:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("18:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("18:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("19:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("19:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("20:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("20:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("21:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("21:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("22:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("22:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("23:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierFerm), _("23:30"));

  AABAcomboboxModifierType = gtk_combo_box_new_text ();
  gtk_widget_show (AABAcomboboxModifierType);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAcomboboxModifierType, 152, 200);
  gtk_widget_set_size_request (AABAcomboboxModifierType, 256, 35);
  gtk_container_set_border_width (GTK_CONTAINER (AABAcomboboxModifierType), 5);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierType), _("Interieur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierType), _("Exterieur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxModifierType), _("Sous-terrain"));

  AABAbuttonModifierAnnuler = gtk_button_new ();
  gtk_widget_show (AABAbuttonModifierAnnuler);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAbuttonModifierAnnuler, 80, 530);
  gtk_widget_set_size_request (AABAbuttonModifierAnnuler, 120, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (AABAbuttonModifierAnnuler), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  AABAbuttonModifierEnregistrer = gtk_button_new ();
  gtk_widget_show (AABAbuttonModifierEnregistrer);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAbuttonModifierEnregistrer, 300, 530);
  gtk_widget_set_size_request (AABAbuttonModifierEnregistrer, 120, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (AABAbuttonModifierEnregistrer), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  AABAlabelModifierError = gtk_label_new ("");
  gtk_widget_show (AABAlabelModifierError);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAlabelModifierError, 50, 480);
  gtk_widget_set_size_request (AABAlabelModifierError, 400, 40);

  AABAcheckbuttonModifier247 = gtk_check_button_new_with_mnemonic (_("24/7"));
  gtk_widget_show (AABAcheckbuttonModifier247);
  gtk_fixed_put (GTK_FIXED (AABAfixedModifier), AABAcheckbuttonModifier247, 160, 304);
  gtk_widget_set_size_request (AABAcheckbuttonModifier247, 120, 24);

  g_signal_connect ((gpointer) AABAwindowModifier, "map",
                    G_CALLBACK (on_AABAwindowModifier_map),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonModifierAnnuler, "clicked",
                    G_CALLBACK (on_AABAbuttonModifierAnnuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonModifierEnregistrer, "clicked",
                    G_CALLBACK (on_AABAbuttonModifierEnregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAcheckbuttonModifier247, "toggled",
                    G_CALLBACK (on_AABAcheckbuttonModifier247_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AABAwindowModifier, AABAwindowModifier, "AABAwindowModifier");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAfixedModifier, "AABAfixedModifier");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAentryModifierNom, "AABAentryModifierNom");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAtextviewModifierLoc, "AABAtextviewModifierLoc");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAspinbuttonModifierNumDePlaces, "AABAspinbuttonModifierNumDePlaces");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAspinbuttonModifierTarif, "AABAspinbuttonModifierTarif");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierLoc, "AABAlabelModifierLoc");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierNumDePlaces, "AABAlabelModifierNumDePlaces");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierHrsDouv, "AABAlabelModifierHrsDouv");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierOuv, "AABAlabelModifierOuv");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierFerm, "AABAlabelModifierFerm");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierTarif, "AABAlabelModifierTarif");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierTitle, "AABAlabelModifierTitle");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierNom, "AABAlabelModifierNom");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierType, "AABAlabelModifierType");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAcomboboxModifierOuv, "AABAcomboboxModifierOuv");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAcomboboxModifierFerm, "AABAcomboboxModifierFerm");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAcomboboxModifierType, "AABAcomboboxModifierType");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAbuttonModifierAnnuler, "AABAbuttonModifierAnnuler");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, image2, "image2");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, label2, "label2");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAbuttonModifierEnregistrer, "AABAbuttonModifierEnregistrer");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, image1, "image1");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, label1, "label1");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAlabelModifierError, "AABAlabelModifierError");
  GLADE_HOOKUP_OBJECT (AABAwindowModifier, AABAcheckbuttonModifier247, "AABAcheckbuttonModifier247");

  return AABAwindowModifier;
}

GtkWidget*
create_AABAwindowGererParking (void)
{
  GtkWidget *AABAwindowGererParking;
  GtkWidget *AABAfixedGererParking;
  GtkWidget *AABAtreeviewGPList;
  GtkWidget *AABAlabelGPParkings;
  GtkWidget *AABAlabelGPTitle;
  GtkWidget *AABAbuttonGPAjouter;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *AABAbuttonGPSupprimer;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label10;
  GtkWidget *AABAbuttonGPModifier;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label9;
  GtkWidget *AABAbuttonGPAgent;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label8;

  AABAwindowGererParking = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AABAwindowGererParking), _("Gerer Parking"));

  AABAfixedGererParking = gtk_fixed_new ();
  gtk_widget_show (AABAfixedGererParking);
  gtk_container_add (GTK_CONTAINER (AABAwindowGererParking), AABAfixedGererParking);
  gtk_widget_set_size_request (AABAfixedGererParking, 500, 600);

  AABAtreeviewGPList = gtk_tree_view_new ();
  gtk_widget_show (AABAtreeviewGPList);
  gtk_fixed_put (GTK_FIXED (AABAfixedGererParking), AABAtreeviewGPList, 8, 128);
  gtk_widget_set_size_request (AABAtreeviewGPList, 480, 350);
  gtk_container_set_border_width (GTK_CONTAINER (AABAtreeviewGPList), 5);
  gtk_widget_set_extension_events (AABAtreeviewGPList, GDK_EXTENSION_EVENTS_ALL);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (AABAtreeviewGPList), TRUE);

  AABAlabelGPParkings = gtk_label_new (_("Liste De Parkings"));
  gtk_widget_show (AABAlabelGPParkings);
  gtk_fixed_put (GTK_FIXED (AABAfixedGererParking), AABAlabelGPParkings, 180, 95);
  gtk_widget_set_size_request (AABAlabelGPParkings, 140, 16);

  AABAlabelGPTitle = gtk_label_new (_("Gerer Parking"));
  gtk_widget_show (AABAlabelGPTitle);
  gtk_fixed_put (GTK_FIXED (AABAfixedGererParking), AABAlabelGPTitle, 144, 24);
  gtk_widget_set_size_request (AABAlabelGPTitle, 208, 24);

  AABAbuttonGPAjouter = gtk_button_new ();
  gtk_widget_show (AABAbuttonGPAjouter);
  gtk_fixed_put (GTK_FIXED (AABAfixedGererParking), AABAbuttonGPAjouter, 368, 510);
  gtk_widget_set_size_request (AABAbuttonGPAjouter, 110, 60);
  gtk_container_set_border_width (GTK_CONTAINER (AABAbuttonGPAjouter), 4);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (AABAbuttonGPAjouter), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  AABAbuttonGPSupprimer = gtk_button_new ();
  gtk_widget_show (AABAbuttonGPSupprimer);
  gtk_fixed_put (GTK_FIXED (AABAfixedGererParking), AABAbuttonGPSupprimer, 20, 510);
  gtk_widget_set_size_request (AABAbuttonGPSupprimer, 110, 60);
  gtk_container_set_border_width (GTK_CONTAINER (AABAbuttonGPSupprimer), 4);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (AABAbuttonGPSupprimer), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);

  AABAbuttonGPModifier = gtk_button_new ();
  gtk_widget_show (AABAbuttonGPModifier);
  gtk_fixed_put (GTK_FIXED (AABAfixedGererParking), AABAbuttonGPModifier, 135, 510);
  gtk_widget_set_size_request (AABAbuttonGPModifier, 110, 60);
  gtk_container_set_border_width (GTK_CONTAINER (AABAbuttonGPModifier), 4);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (AABAbuttonGPModifier), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);

  AABAbuttonGPAgent = gtk_button_new ();
  gtk_widget_show (AABAbuttonGPAgent);
  gtk_fixed_put (GTK_FIXED (AABAfixedGererParking), AABAbuttonGPAgent, 250, 510);
  gtk_widget_set_size_request (AABAbuttonGPAgent, 110, 60);
  gtk_container_set_border_width (GTK_CONTAINER (AABAbuttonGPAgent), 4);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (AABAbuttonGPAgent), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("  Attribuer\n     Agent"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) AABAwindowGererParking, "map",
                    G_CALLBACK (on_AABAwindowGererParking_map),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonGPAjouter, "clicked",
                    G_CALLBACK (on_AABAbuttonGPAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonGPSupprimer, "clicked",
                    G_CALLBACK (on_AABAbuttonGPSupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonGPModifier, "clicked",
                    G_CALLBACK (on_AABAbuttonGPModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonGPAgent, "clicked",
                    G_CALLBACK (on_AABAbuttonGPAgent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AABAwindowGererParking, AABAwindowGererParking, "AABAwindowGererParking");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAfixedGererParking, "AABAfixedGererParking");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAtreeviewGPList, "AABAtreeviewGPList");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAlabelGPParkings, "AABAlabelGPParkings");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAlabelGPTitle, "AABAlabelGPTitle");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAbuttonGPAjouter, "AABAbuttonGPAjouter");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, image7, "image7");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, label7, "label7");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAbuttonGPSupprimer, "AABAbuttonGPSupprimer");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, image10, "image10");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, label10, "label10");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAbuttonGPModifier, "AABAbuttonGPModifier");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, image9, "image9");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, label9, "label9");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, AABAbuttonGPAgent, "AABAbuttonGPAgent");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, image8, "image8");
  GLADE_HOOKUP_OBJECT (AABAwindowGererParking, label8, "label8");

  return AABAwindowGererParking;
}

GtkWidget*
create_AABAwindowAttribuerAgent (void)
{
  GtkWidget *AABAwindowAttribuerAgent;
  GtkWidget *AABAfixedAG;
  GtkWidget *AABAlabelAGTitle;
  GtkWidget *AABAbuttonAGAttribuer;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *AABAbuttonAGAnnuler;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *AABAlabelAGAgentId;
  GtkWidget *AABAcomboboxentryAGAgentId;
  GtkWidget *AABAlabelAGParkingName;
  GtkWidget *AABAlabelAGError;

  AABAwindowAttribuerAgent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AABAwindowAttribuerAgent), _("Attribuer Agent"));

  AABAfixedAG = gtk_fixed_new ();
  gtk_widget_show (AABAfixedAG);
  gtk_container_add (GTK_CONTAINER (AABAwindowAttribuerAgent), AABAfixedAG);
  gtk_widget_set_size_request (AABAfixedAG, 400, 400);

  AABAlabelAGTitle = gtk_label_new (_("Attribuer Agent au parking:"));
  gtk_widget_show (AABAlabelAGTitle);
  gtk_fixed_put (GTK_FIXED (AABAfixedAG), AABAlabelAGTitle, 90, 40);
  gtk_widget_set_size_request (AABAlabelAGTitle, 220, 17);

  AABAbuttonAGAttribuer = gtk_button_new ();
  gtk_widget_show (AABAbuttonAGAttribuer);
  gtk_fixed_put (GTK_FIXED (AABAfixedAG), AABAbuttonAGAttribuer, 220, 330);
  gtk_widget_set_size_request (AABAbuttonAGAttribuer, 120, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (AABAbuttonAGAttribuer), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Attribuer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  AABAbuttonAGAnnuler = gtk_button_new ();
  gtk_widget_show (AABAbuttonAGAnnuler);
  gtk_fixed_put (GTK_FIXED (AABAfixedAG), AABAbuttonAGAnnuler, 55, 330);
  gtk_widget_set_size_request (AABAbuttonAGAnnuler, 120, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (AABAbuttonAGAnnuler), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  AABAlabelAGAgentId = gtk_label_new (_("Agent\n"));
  gtk_widget_show (AABAlabelAGAgentId);
  gtk_fixed_put (GTK_FIXED (AABAfixedAG), AABAlabelAGAgentId, 20, 130);
  gtk_widget_set_size_request (AABAlabelAGAgentId, 99, 17);

  AABAcomboboxentryAGAgentId = gtk_combo_box_entry_new_text ();
  gtk_widget_show (AABAcomboboxentryAGAgentId);
  gtk_fixed_put (GTK_FIXED (AABAfixedAG), AABAcomboboxentryAGAgentId, 112, 130);
  gtk_widget_set_size_request (AABAcomboboxentryAGAgentId, 220, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxentryAGAgentId), _("Agent1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxentryAGAgentId), _("Agent2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AABAcomboboxentryAGAgentId), _("Agent3"));

  AABAlabelAGParkingName = gtk_label_new ("");
  gtk_widget_show (AABAlabelAGParkingName);
  gtk_fixed_put (GTK_FIXED (AABAfixedAG), AABAlabelAGParkingName, 48, 72);
  gtk_widget_set_size_request (AABAlabelAGParkingName, 300, 17);

  AABAlabelAGError = gtk_label_new ("");
  gtk_widget_show (AABAlabelAGError);
  gtk_fixed_put (GTK_FIXED (AABAfixedAG), AABAlabelAGError, 48, 272);
  gtk_widget_set_size_request (AABAlabelAGError, 300, 30);

  g_signal_connect ((gpointer) AABAwindowAttribuerAgent, "map",
                    G_CALLBACK (on_AABAwindowAttribuerAgent_map),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonAGAttribuer, "clicked",
                    G_CALLBACK (on_AABAbuttonAGAttribuer_clicked),
                    NULL);
  g_signal_connect ((gpointer) AABAbuttonAGAnnuler, "clicked",
                    G_CALLBACK (on_AABAbuttonAGAnnuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AABAwindowAttribuerAgent, AABAwindowAttribuerAgent, "AABAwindowAttribuerAgent");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAfixedAG, "AABAfixedAG");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAlabelAGTitle, "AABAlabelAGTitle");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAbuttonAGAttribuer, "AABAbuttonAGAttribuer");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, image5, "image5");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, label5, "label5");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAbuttonAGAnnuler, "AABAbuttonAGAnnuler");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, image6, "image6");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, label6, "label6");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAlabelAGAgentId, "AABAlabelAGAgentId");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAcomboboxentryAGAgentId, "AABAcomboboxentryAGAgentId");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAlabelAGParkingName, "AABAlabelAGParkingName");
  GLADE_HOOKUP_OBJECT (AABAwindowAttribuerAgent, AABAlabelAGError, "AABAlabelAGError");

  return AABAwindowAttribuerAgent;
}

